### ISSUE TITLE
ERROR -- element of type GCMQ not known

### ISSUE THREAD

**Issue by akki21686** [TLCFEM/gcmq-opensees-implementation#1]
I get following error when using GCMQ with opensees version 3.2.2 64bit

checking library: OPS_GCMQ
ERROR -- element of type GCMQ not known

**Comment by TLCFEM** [comment]
Looks like the interface has been updated between version 2.5.0 and 3.2.2. The x64 executable (`binary/OpenSees.exe`) is recompiled with GCMQ, please check if that works.

**Comment by TLCFEM** [comment]
I am closing this issue for the moment. If there are any further issues please feel free to reopen it.
